name: plan

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.7.0
        with:
          egress-policy: audit

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Setup Teraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Prettify
        run: terraform fmt -check
        continue-on-error: true

      - name: Initialise
        run: terraform init

      - name: Validate
        run: terraform validate -no-color

  tflint:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.7.0
        with:
          egress-policy: audit

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Cache Plugins
        uses: actions/cache@v4
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.46.1

      - name: Initialise
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Lint
        run: tflint -f compact

  trivy:
    runs-on: ubuntu-latest

    env:
      trivy_sarif: trivy.sarif

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.7.0
        with:
          egress-policy: audit

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Run with SARIF Output
        uses: aquasecurity/trivy-action@0.19.0
        with:
          scan-type: "fs"
          format: "sarif"
          output: ${{ env.trivy_sarif }}

      - name: Report via GitHub CodeQL
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file:  ${{ env.trivy_sarif }}
